-- ==============================================================================
-- SCHEMA SUPABASE (POSTGRESQL) - GESTÃO SAAS MULTI-TENANT
-- Execute este script no SQL Editor do seu projeto Supabase (supabase.com)
-- ==============================================================================

-- 1. Habilitar extensões necessárias
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABELA DE EMPRESAS (TENANTS)
CREATE TABLE IF NOT EXISTS public.empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social TEXT NOT NULL,
    nome_fantasia TEXT NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    email TEXT NOT NULL,
    telefone VARCHAR(30),
    endereco TEXT,
    cidade VARCHAR(100),
    estado VARCHAR(2),
    status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovada', 'rejeitada', 'suspensa')),
    logo_url TEXT,
    banner_url TEXT,
    cor_tema VARCHAR(20) DEFAULT '#2563eb',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Índices de busca rápida
CREATE INDEX IF NOT EXISTS idx_empresas_cnpj ON public.empresas (cnpj);
CREATE INDEX IF NOT EXISTS idx_empresas_status ON public.empresas (status);

-- 3. TABELA DE USUÁRIOS
CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT REFERENCES public.empresas(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    senha TEXT NOT NULL,
    perfil TEXT NOT NULL DEFAULT 'funcionario' CHECK (perfil IN ('admin', 'dono', 'gerente', 'funcionario')),
    cargo VARCHAR(100),
    departamento VARCHAR(100),
    ativo BOOLEAN NOT NULL DEFAULT true,
    ultimo_acesso TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_usuarios_empresa ON public.usuarios (empresa_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON public.usuarios (email);
CREATE INDEX IF NOT EXISTS idx_usuarios_perfil ON public.usuarios (perfil);

-- 4. TABELA DE PRODUTOS
CREATE TABLE IF NOT EXISTS public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    sku VARCHAR(60) NOT NULL,
    codigo_barras VARCHAR(100),
    categoria VARCHAR(100) NOT NULL DEFAULT 'Geral',
    preco_custo NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    preco_venda NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    estoque_atual INTEGER NOT NULL DEFAULT 0,
    estoque_minimo INTEGER NOT NULL DEFAULT 5,
    unidade_medida VARCHAR(10) NOT NULL DEFAULT 'UN',
    localizacao VARCHAR(100),
    foto_url TEXT,
    ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_empresa_sku UNIQUE (empresa_id, sku)
);

CREATE INDEX IF NOT EXISTS idx_produtos_empresa ON public.produtos (empresa_id);
CREATE INDEX IF NOT EXISTS idx_produtos_sku ON public.produtos (sku);
CREATE INDEX IF NOT EXISTS idx_produtos_categoria ON public.produtos (categoria);

-- 5. TABELA DE MOVIMENTAÇÕES DE ESTOQUE (KARDEX)
CREATE TABLE IF NOT EXISTS public.movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    produto_id BIGINT NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
    usuario_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('entrada', 'saida', 'ajuste', 'devolucao')),
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    saldo_anterior INTEGER NOT NULL,
    saldo_posterior INTEGER NOT NULL,
    motivo TEXT NOT NULL,
    documento_ref VARCHAR(100),
    valor_unitario NUMERIC(12, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_mov_empresa ON public.movimentacoes_estoque (empresa_id);
CREATE INDEX IF NOT EXISTS idx_mov_produto ON public.movimentacoes_estoque (produto_id);
CREATE INDEX IF NOT EXISTS idx_mov_created_at ON public.movimentacoes_estoque (created_at DESC);

-- 6. TABELA DE TICKETS DE SUPORTE
CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    usuario_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
    titulo TEXT NOT NULL,
    categoria TEXT NOT NULL,
    prioridade TEXT NOT NULL DEFAULT 'media' CHECK (prioridade IN ('baixa', 'media', 'alta', 'urgente')),
    status TEXT NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto', 'em_atendimento', 'resolvido', 'fechado')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_tickets_empresa ON public.tickets (empresa_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON public.tickets (status);

-- 7. TABELA DE MENSAGENS DOS TICKETS
CREATE TABLE IF NOT EXISTS public.ticket_mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    usuario_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
    usuario_nome TEXT NOT NULL,
    usuario_perfil TEXT NOT NULL,
    mensagem TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_mensagens_ticket ON public.ticket_mensagens (ticket_id);

-- 8. TRIGGER AUTOMÁTICO PARA ATUALIZAR 'updated_at'
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at_empresas ON public.empresas;
CREATE TRIGGER set_updated_at_empresas
    BEFORE UPDATE ON public.empresas
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_usuarios ON public.usuarios;
CREATE TRIGGER set_updated_at_usuarios
    BEFORE UPDATE ON public.usuarios
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_produtos ON public.produtos;
CREATE TRIGGER set_updated_at_produtos
    BEFORE UPDATE ON public.produtos
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_tickets ON public.tickets;
CREATE TRIGGER set_updated_at_tickets
    BEFORE UPDATE ON public.tickets
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- 9. SEGURANÇA (Row Level Security - RLS)
-- Permite leitura e escrita públicas via chave anon enquanto em desenvolvimento
ALTER TABLE public.empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimentacoes_estoque ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_mensagens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso total empresas anon" ON public.empresas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total usuarios anon" ON public.usuarios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total produtos anon" ON public.produtos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total movimentacoes anon" ON public.movimentacoes_estoque FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total tickets anon" ON public.tickets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total ticket_mensagens anon" ON public.ticket_mensagens FOR ALL USING (true) WITH CHECK (true);

-- 10. CONCESSÃO DE PERMISSÕES PARA AS ROLES DO SUPABASE (anon, authenticated, service_role)
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;

